<?
	$id_bask=$_COOKIE["id_bask"];
	session_start();

	$title="Ваша корзина";
	include("header.phtml");
	include("connect.phtml");
	
	$strSQL1="SELECT COUNT(*) as count FROM basket_bouq WHERE
		id_bask='".$id_bask."'";
	$result1=mysql_query($strSQL1) or die
		("Не получается выполнить запрос к корзине :(");
		$row=mysql_fetch_array($result1);
		if($row["count"]==0)
		{?>
			<table border="1" width="100%" align="right" style="position:absolute; top:80; left: 0%; background: rgb(216, 191, 216)">
				<tr>
					<td align="center">
						<b>Ваша корзина пуста!</b>
					</td>
				</tr>
			</table>
		<?}
		
		else
		{
			$strSQL1="SELECT image_bq, comp_bq, name_bq, price_bq, id_bask, kolvo, bouquets.id_bq FROM bouquets, basket_bouq WHERE bouquets.id_bq=basket_bouq.id_bq AND id_bask='".$id_bask."'";
			$result1=mysql_query($strSQL1) or die
				("Не получается выполнить запрос к непустой корзине :(");
		?>
			<table border="1" width="100%" align="right" style="position:absolute; top:80; left: 0%; background: rgb(216, 191, 216, 0.7); border-spacing: 10px; border-collapse: collapse;">
				<tr>
					<td align="center">
						<i>Название</i>
					</td>
					<td align="center">
						<i>Описание</i>
					</td>
					<td align="center">
						<i>Цена</i>
					</td>
					<td align="center">
						<i>Количество</i>
					</td>
				</tr>
		<?
			$sum=0;
			while($row=mysql_fetch_array($result1))
			{?>
				<tr>
					<td>
						<?print $row["name_bq"];?>
					</td>
					<td>
						<?print $row["comp_bq"];?>
					</td>
					<td align="right">
						<?print $row["price_bq"];?>
					</td>
					<td align="center">
						<?print $row["kolvo"];?>
						<a href="dobasket.phtml?type=1&id_bq=
							<?print $row["id_bq"];?>" title="Увеличить">[ + ]</a>
						<a href="dobasket.phtml?type=2&id_bq=
							<?print $row["id_bq"];?>" title="Уменьшить">[ - ]</a>	

					</td>
					<td width="5%">
						<a href="dobasket.phtml?type=3&id_bq=
							<?print $row["id_bq"];?>"><img src="../images/delete.png" width="30"/></a>
					</td>
				</tr>
				<?
					$sum=$sum+$row["price_bq"]*$row["kolvo"];
				}?>
				<tr>
					<td align="right"></td>
					<td align="right">
						<i>Итого: </i>
					</td>
					<td align="right"><i>
						<?print $sum;?>
					</i></td>
					<td></td><td></td>
				</tr>
				<tr>
					<td colspan="5">
						<center>
							<a href=dobasket.phtml?type=4>
								<b>Очистить корзину</b>
							</a>
						</center>
					</td>
				</tr>
			</table>
		<?
			} include("footer.phtml");
		?>