<? 
	$title="Добро пожаловать!";
	include("header.phtml");
?>

<form action="auto.phtml" method="POST">
	<table style="position:fixed; top:30%; left:40%">
		<tr>
			<td align="center"><font size="+2" color="#FFF5EE" style="text-shadow: #4C154C 0 0 2px;"><b>Логин</b></font></td>
		</tr>
		<tr>
			<td align="left"><input type="text" style="width:250; height:25;" name="login"/></td>
		</tr>
		<tr>
			<td align="center"><font size="+2" color="#FFF5EE" style="text-shadow: #4C154C 0 0 2px;"><b>Пароль</b></font></td>
		</tr>
		<tr>
			<td align="left"><input type="password" style="width:250; height:25;" name="pass"/>
		</tr>
		<tr>
			<td align="center"><input type="submit" value="Войти" style="width:60; height:20;"/></td>
		</tr>
	</table>
</form>
<? include("footer.phtml");?>